# Site
name: 'SEA COMO SEO'
title: 'SEA COMO SEO'
description: 'Tutoriales y trucos de SEO, Diseño Web y Desarrollo'
url: https://lorensansol.github.io
baseurl: /seacomoseo.com
logo: /assets/img/logo-sea-como-seo.png
favicon: /assets/img/logo-sea-como-seo.png
google_analytics: UA-75330923-2
google_site_verification: 'Sb-MUAYWclN8UdYEC0-7YsKPFBAsrAPYNmM-k5QOXak'
# google_adsense: "ca-pub-7914952536979255" # ca-pub-xxxxxxxxxxxxxxxx
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
email: '&#x73;&#x65;&#x61;&#x63;&#x6F;&#x6D;&#x6F;&#x73;&#x65;&#x6F;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;'
disqus: 'seacomoseo'
lang: es
permalink: /:title
authorbox: true
author-links: true
search: true
lazy-load-comments: false # if not, comments load when clic
critical-path-css: false

# Authors
authors:
  sal:
    name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: 'Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo.'
  john:
    name: John
    avatar: /assets/img/avatar.png
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: 'This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages.'
  loren:
    name: Loren San Sol
    avatar: /assets/img/loren-san-sol-scs.jpg
    gravatar: a48d43c9530f50721162853c0b68aebc
    # email: '&#x6C;&#x6F;&#x72;&#x65;&#x6E;&#x73;&#x61;&#x6E;&#x73;&#x6F;&#x6C;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;'
    # web: https://seacomoseo.com/
    # twitter: https://twitter.com/lorensansol
    description: 'SEO y maquetación web son mis especialidades. Desarrollo web es lo que me pone. ¡Y en eso estamos!'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categorias#:name'

# Pagination
paginate: 6
paginate_path: /page:num/

# Drafts and pages like collections
collections:
  drafts:
    output: true
  pages:
    output: true
    permalink: /:name

# Compress HTML
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: [development]

# Exclude
exclude: [README.md, Gemfile, Gemfile.lock]

# Defaults values
defaults:
  - # All posts
    scope:
      path: ''
      type: 'posts'
    values:
      layout: post
      author: loren
      toc: true
      description: false
      comments: true
  - # All posts
    scope:
      path: ''
      type: 'drafts'
    values:
      layout: post
      author: loren
      toc: true
      description: false
      comments: false
      sitemap: false
  - # All pages
    scope:
      path: ''
      type: 'pages'
    values:
      layout: page
      toc: false
      description: false
      comments: false
      sitemap: false
  - # Neither noindex nor sitemap in pages
    scope:
      path: 'page'
    values:
      sitemap: false

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# DEVELOPMENT CONFIG IN _config_dev.yml