# Site
name: 'SEA COMO SEO'
title: 'SEA COMO SEO'
description: 'Tutoriales y trucos de SEO, Diseño Web y Desarrollo'
logo: 'assets/images/logo-sea-como-seo.png'
favicon: 'assets/images/logo-sea-como-seo.png'
baseurl: /seacomoseo.com
google_analytics: #'UA-xxxxxxxx-1'
google_site_verification: #
lang: es
disqus: 'seacomoseo'
mailchimp-list: # 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ['_pages']
permalink: /:title
email: '&#x73;&#x65;&#x61;&#x63;&#x6F;&#x6D;&#x6F;&#x73;&#x65;&#x6F;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;' # seacomoseo@gmail.com
search: true

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: 'Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo.'
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: 'This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages.'
  loren:
    name: Loren
    display_name: Loren
    gravatar: a48d43c9530f50721162853c0b68aebc
    # email: '&#x6C;&#x6F;&#x72;&#x65;&#x6E;&#x73;&#x61;&#x6E;&#x73;&#x6F;&#x6C;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;' # lorensansol@gmail.com
    # web: https://seacomoseo.com/
    # twitter: https://twitter.com/lorensansol
    description: 'SEO y maquetación web son mis especialidades. Desarrollo web es lo que me pone. ¡Y en eso estamos!'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categorias#:name'

# Pagination
paginate: 6
paginate_path: /page:num/
seo_paginator_message: 'Página %<current>s de %<total>s | '

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to 'enabled' to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client: 'ca-pub-3412143450191416'
adsense-data-ad-slot: '1363087678'

# Lazy Images ('enabled' or 'disabled')
lazyimages: 'disabled'

# Post Author Box ('enabled' or 'disabled')
authorbox: 'enabled'

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Compress HTML
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: [development]

# Defaults values
defaults:
  - # All posts
    scope:
      path: ''
      type: 'posts'
    values:
      layout: post
      author: loren
      toc: true
      description: false
      comments: true
  - # All pages
    scope:
      path: ''
      type: 'pages'
    values:
      layout: page
      toc: true
      description: false
      comments: false
      # permalink: /:name
  - # Neither noindex nor sitemap in pages
    scope:
      path: 'page'
    values:
      sitemap: false

# Exclude
exclude: [README.md, Gemfile, Gemfile.lock]